export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_ERROR="USER_LOGIN_ERROR"

export const USER_DATA_REQUEST="USER_DATA_REQUEST"
export const USER_DATA_SUCCESS="USER_DATA_SUCCESS"
export const USER_DATA_ERROR="USER_DATA_ERROR"